import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import styles from '../styles/Home.module.css';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Rinzo Testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <footer className={styles.footer}>
        Powered by Rinzo
      </footer>
    </>
  );
}

export default MyApp;
